spring:
    application:
        name: kyobokngbook
    profiles:
        active: dev
    datasource:
        url: jdbc:mysql://localhost:3306/dev2
        username: root
        password: 1q2w3e4r
    jpa:
        hibernate:
            ddl-auto: update # 데이터베이스 스키마 자동 생성 또는 업데이트
            naming:
                physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # 카멜케이스 치환
        show-sql: true # 쿼리문 확인 가능
    flyway:
        enabled: true
        baseline-on-migrate: true          #  flyway_schema_history 테이블을 자동으로 생성할지 여부 적용하지 않은  DB 만
---
server:
    port: 8080
