spring:
    application:
        name: kyobokngbook
    profiles:
        active: dev
    datasource:
        url: jdbc:mysql://localhost:3306/dev
        username: root
        password: 1q2w3e4r
    jpa:
        hibernate:
            ddl-auto: validate # 정상 매핑여부만 체크
            naming:
                physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # 카멜케이스 치환
        show-sql: true # 쿼리문 확인 가능
        properties:
          hibernate:
            default_batch_fetch_size: 50
            jdbc:
                batch_size: 1000
    flyway:
        enabled: true
        baseline-on-migrate: true          #  flyway_schema_history 테이블을 자동으로 생성할지 여부 적용하지 않은  DB 만
    devtools:
        remote:
            restart:
                enabled: false
---
server:
    port: 8080
